export const locations = {
	marmaris: {
		name: "Marmaris",
		region: "Muğla",
		slug: "marmaris",
		lat: "36.8555",
		lng: "28.2719",
		description: "Marmaris, dünyaca ünlü marinası, kristal körfezi ve canlı turizm altyapısıyla Muğla'nın en dinamik destinasyonlarından biridir.",
		services: {
			drone: {
				title: "Marmaris Drone Çekimi",
				metaDesc: "Marmaris'te profesyonel drone çekimi. Marina, körfez, tekne ve yat, otel ve emlak için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Marmaris Kalesi'nden körfeze uzanan panoramayı, dünyanın sayılı marinalarından birini ve turkuaz suları havadan görüntüleyin.",
				badges: ["Marina", "Körfez", "Tekne & Yat", "Otel", "Düğün", "Etkinlik"],
				intro: "Marmaris, yılda 2 milyonu aşkın turist ağırlayan, Türkiye'nin en büyük marinasına ev sahipliği yapan ve uluslararası yatçılığın gözdesi bir destinasyondur. Bu ölçekteki bir pazarda öne çıkmak için profesyonel drone görüntüleri artık tercih değil, zorunluluktur.",
				details: "Marmaris Kalesi çevresindeki tarihi doku, körfezi çevreleyen çam ormanları ve marina sırasındaki yüzlerce yat — tüm bu görsel zenginliği yalnızca havadan bir çekimle tek karede yakalamak mümkündür. Otel tanıtımlarından tekne kiralama ilanlarına, düğün filmlerinden kurumsal tanıtım videolarına kadar her ihtiyaca özel paketler sunuyoruz.",
				areas: [
					{ icon: "⛵", title: "Marina & Yat Çekimi", desc: "Marmaris Marinası'ndaki yatlar, guletler ve yelkenliler için tanıtım ve satış amaçlı hava çekimleri." },
					{ icon: "🏨", title: "Otel & Resort Çekimi", desc: "5 yıldızlı oteller ve tatil köyleri için pazarlama amaçlı drone videoları ve fotoğraf paketleri." },
					{ icon: "🏡", title: "Villa & Emlak", desc: "Marmaris ve Armutalan bölgesindeki villa ve daireler için satış ilanı çekimleri." },
					{ icon: "🎉", title: "Düğün & Etkinlik", desc: "Marmaris'teki açık hava düğünleri ve organizasyonlar için sinematik hava çekimleri." },
				],
				faq: [
					{ q: "Marmaris'te drone çekimi için izin gerekli mi?", a: "Marmaris merkez ve belirli sahil bölgelerinde SHGM izni gerekmektedir. Tüm izin süreçleri bizim tarafımızdan takip edilir." },
					{ q: "Bodrum'dan Marmaris'e geliyor musunuz?", a: "Evet. Marmaris çekimleri için Bodrum'dan hareket edilir. Ulaşım ücreti teklif aşamasında netleştirilir." },
				],
			},
			photo: {
				title: "Marmaris Emlak ve Tekne Fotoğraf Çekimi",
				metaDesc: "Marmaris'te profesyonel emlak fotoğrafçılığı. Villa, daire, tekne ve yat fotoğraf & video çekimi. Satışlarınızı hızlandırın. Cihan Duran.",
				heroDesc: "Marmaris'teki mülkünüzü veya teknenizi rakiplerinizden ayrıştıran, alıcıyı harekete geçiren profesyonel görüntülerle sunun.",
				badges: ["Villa", "Tekne", "Marina", "Otel", "Airbnb", "Sahibinden"],
				intro: "Marmaris emlak piyasası, uluslararası alıcıların yoğun ilgi gösterdiği rekabetçi bir pazardır. İngilizce, Rusça ve Almanca konuşan alıcılar satın alma kararının büyük bölümünü çevrimiçi görüntülere bakarak verirler. Bu nedenle Marmaris'te profesyonel fotoğraf, satış sürecinin en kritik adımıdır.",
				details: "Villa, daire veya teknenizi doğru ışık koşullarında, geniş açı ve hassas renk yönetimiyle çekiyoruz. İç mekan ve dış cephe çekimlerini havadan görüntülerle tamamlayarak alıcıya konumu, çevreyi ve mülkü aynı anda gösteriyoruz.",
				areas: [
					{ icon: "🏡", title: "Villa & Müstakil", desc: "Marmaris ve Armutalan'daki lüks villaların satış ve kiralama ilanlarına yönelik çekimler." },
					{ icon: "⛵", title: "Tekne & Gulet", desc: "Marina'da veya körfezde tekne, gulet ve yat fotoğraf & video çekimleri." },
					{ icon: "🏢", title: "Daire & Residence", desc: "Geniş açı çekim teknikleriyle ferah ve cazip iç mekan görselleri." },
					{ icon: "🏠", title: "Airbnb & Kiralık", desc: "Kısa dönem kiralık mülkler için platform bazlı optimize çekim paketleri." },
				],
				faq: [
					{ q: "Marmaris'e ne zaman geliniz?", a: "Hafta içi ve hafta sonu randevu alınabilir. Marmaris çekimleri için en az 3 gün öncesinden randevu oluşturulması önerilir." },
					{ q: "Yabancı dilde iletişim sağlayabiliyor musunuz?", a: "Temel düzeyde İngilizce iletişim sağlanabilir. Uluslararası alıcılar için bu avantajlı olabilir." },
				],
			},
			web: {
				title: "Marmaris Web Tasarım ve Yazılım Geliştirme",
				metaDesc: "Marmaris'te profesyonel web tasarım ve yazılım geliştirme. Otel, tekne kiralama ve turizm işletmeleri için SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Marmaris'teki turizm, tekne kiralama veya emlak işletmeniz için uluslararası standartlarda, çok dilli web sitesi çözümleri.",
				badges: ["Turizm", "Tekne Kiralama", "Otel", "E-Ticaret", "Çok Dilli", "SEO"],
				intro: "Marmaris'te faaliyet gösteren bir işletme, yalnızca Türk değil; İngiliz, Alman, Rus ve Hollandalı turistlere de hitap etmek zorundadır. Bu nedenle çok dilli, hızlı ve uluslararası ödeme sistemleriyle entegre web siteleri Marmaris pazarının zorunluluğudur.",
				details: "Tekne kiralama rezervasyon sistemlerinden otel booking entegrasyonlarına, emlak ilan platformlarından kurumsal tanıtım sitelerine kadar Marmaris'in ihtiyaçlarını bilen bir perspektifle web çözümleri geliştiriyoruz. Google'da 'Marmaris boat rental', 'Marmaris villa for sale' gibi anahtar kelimelerde görünür olmanız için SEO altyapısı tasarımın başından itibaren entegre edilir.",
				areas: [
					{ icon: "⛵", title: "Tekne Kiralama Sitesi", desc: "Online rezervasyon, fiyat takvimi ve ödeme entegrasyonlu tekne kiralama platformları." },
					{ icon: "🏨", title: "Otel & Pansiyon", desc: "Booking.com ve Airbnb alternatifleri olan direkt rezervasyon siteleri." },
					{ icon: "🏡", title: "Emlak Sitesi", desc: "İngilizce ve Almanca destekli uluslararası alıcılara yönelik emlak portalları." },
					{ icon: "🛒", title: "E-Ticaret", desc: "Marmaris'ten dünyaya satış yapabileceğiniz güvenli e-ticaret çözümleri." },
				],
				faq: [
					{ q: "Çok dilli site yapıyor musunuz?", a: "Evet. Türkçe, İngilizce ve ihtiyaca göre Almanca, Rusça dil desteği sunabiliyoruz." },
					{ q: "Marmaris'te yüz yüze toplantı mümkün mü?", a: "Bodrum bazlı çalışıyorum, ancak Marmaris'e proje başlangıcı için ziyaret düzenlenebilir." },
				],
			},
			design: {
				title: "Marmaris Grafik Tasarım — Logo ve Kurumsal Kimlik",
				metaDesc: "Marmaris'te profesyonel grafik tasarım. Logo tasarımı, kurumsal kimlik, sosyal medya ve baskı materyalleri. Cihan Duran.",
				heroDesc: "Marmaris'in uluslararası turizm pazarında markanızı güçlü kılacak logo ve kurumsal kimlik tasarımları.",
				badges: ["Logo", "Otel Kimliği", "Sosyal Medya", "Baskı", "Menü Tasarımı"],
				intro: "Marmaris'te faaliyet gösteren bir restoran, otel, tekne kiralama şirketi veya butik mağaza uluslararası bir müşteri kitlesine hitap eder. Bu pazarda marka görselliği; menüden tabelaya, sosyal medyadan ambalaja kadar tutarlı ve profesyonel olmak zorundadır.",
				details: "Yabancı turistlerin yoğun ilgi gösterdiği Marmaris pazarında markanızın ilk izlenimi belirleyicidir. Sektörünüze ve hedef kitlenize özgü renk paleti, tipografi ve görsel kimlik çalışmasıyla sizi rakiplerinizden ayrıştırıyoruz.",
				areas: [
					{ icon: "✏️", title: "Logo & Kimlik", desc: "Otel, restoran ve tekne kiralama işletmeleri için uluslararası standartlarda logo." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Instagram, Facebook ve TikTok için sezonluk içerik şablonları." },
					{ icon: "🍽️", title: "Menü Tasarımı", desc: "Restoran ve bar menüsü tasarımı, çok dilli baskıya hazır formatlar." },
					{ icon: "🖨️", title: "Baskı Materyalleri", desc: "Broşür, afiş, kartvizit ve tanıtım materyalleri." },
				],
				faq: [
					{ q: "Marmaris'teki işletmem için ne kadar sürede logo hazırlanır?", a: "Standart logo paketi 5–7 iş günü. Acil paket 2–3 iş günü." },
					{ q: "Çok dilli menü tasarımı yapıyor musunuz?", a: "Evet, Türkçe/İngilizce/Almanca/Rusça menü tasarımı yapılmaktadır." },
				],
			},
		},
	},

	fethiye: {
		name: "Fethiye",
		region: "Muğla",
		slug: "fethiye",
		lat: "36.6220",
		lng: "29.1168",
		description: "Fethiye; Ölüdeniz'i, 12 Ada turu güzergahı ve Göcek koylarıyla Türkiye'nin en çok ziyaret edilen doğal güzelliklerini barındırır.",
		services: {
			drone: {
				title: "Fethiye Drone Çekimi",
				metaDesc: "Fethiye'de profesyonel drone çekimi. Ölüdeniz, Göcek, 12 Ada, tekne ve emlak için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Ölüdeniz'in eşsiz mavisi, Göcek koylarının sırlı güzelliği ve 12 Ada'nın muhteşem siluetini havadan görüntüleyin.",
				badges: ["Ölüdeniz", "Göcek", "12 Ada", "Tekne", "Paraşüt", "Doğa"],
				intro: "Fethiye, Türkiye'nin en fotojenik destinasyonlarından biridir. Dünyaca ünlü Ölüdeniz Mavi Lagün, Göcek'in el değmemiş koyları ve 12 Ada turu güzergahı; profesyonel drone çekimi için eşsiz bir coğrafya sunar. Bu görüntüler turizm tanıtımından emlak satışına kadar her alanda rakipsiz pazarlama materyalleri oluşturur.",
				details: "Göcek'teki lüks yelkenli ve motor yat çekimlerinden Çalış sahilindeki apart otellerine, Hisarönü'ndeki villalardan Kayaköy çevresindeki tarihi dokuya kadar Fethiye'nin tüm bölgelerinde profesyonel hava çekimi gerçekleştiriyoruz.",
				areas: [
					{ icon: "🌊", title: "Ölüdeniz & Mavi Lagün", desc: "Dünyanın sayılı en güzel plajları arasında gösterilen Ölüdeniz'in havadan görüntüleri." },
					{ icon: "⛵", title: "Göcek Tekneleri", desc: "Göcek marinasındaki yat ve yelkenliler ile koy çekimleri." },
					{ icon: "🏡", title: "Emlak & Villa", desc: "Hisarönü, Çalış ve Göcek'teki villa ve mülkler için satış amaçlı çekimler." },
					{ icon: "🌿", title: "Doğa & Turizm", desc: "Kelebek Vadisi, Saklıkent ve Kayaköy gibi doğal alanlar için tanıtım çekimleri." },
				],
				faq: [
					{ q: "Ölüdeniz'de drone çekimi mümkün mü?", a: "Ölüdeniz tabiat parkı özel koruma alanıdır. Çekim için Orman İdaresi ve SHGM izni gerekmektedir. Bu süreçleri biz yönetiyoruz." },
					{ q: "Göcek marina çekimleri için marina izni gerekiyor mu?", a: "Marina sahasında çekim yapabilmek için marina yönetiminden izin alınması gerekir; bu süreç çekim öncesi planlanır." },
				],
			},
			photo: {
				title: "Fethiye Emlak ve Tekne Fotoğraf Çekimi",
				metaDesc: "Fethiye'de profesyonel emlak fotoğrafçılığı. Villa, daire, tekne ve yat fotoğraf & video çekimi. Göcek, Hisarönü, Çalış. Cihan Duran.",
				heroDesc: "Göcek'teki lüks yatınızı, Hisarönü'ndeki villanızı veya Çalış'taki apart dairenizi en iyi ışıkta sunun.",
				badges: ["Göcek", "Hisarönü", "Çalış", "Ölüdeniz", "Tekne", "Villa"],
				intro: "Fethiye'nin birbirinden farklı bölgeleri — Göcek'in uluslararası yatçı kitlesi, Hisarönü'nün paket tur pazarı, Çalış'ın aile tatili profili — her biri farklı bir pazarlama stratejisi gerektiren emlak ortamları oluşturur. Doğru fotoğraf, doğru alıcıyla buluşmanızı sağlar.",
				details: "Göcek marinasındaki lüks motorsailetin veya teknenizdeki derin ahşap kaplamaların, maun iç dekorasyonun ve güverte ekipmanlarının ayrıntılarını yakalamak için profesyonel lens ve ışık ekipmanı kullanıyoruz. Emlak çekimlerinde sabah ışığından veya altın saatin sıcak tonlarından maksimum fayda sağlıyoruz.",
				areas: [
					{ icon: "⛵", title: "Göcek Tekne & Yat", desc: "Göcek'teki motor yatlar, yelkenliler ve guletler için uluslararası alıcıya yönelik çekimler." },
					{ icon: "🏡", title: "Hisarönü & Ovacık Villalar", desc: "Tatil kiralık ve satılık villalar için yüksek çözünürlüklü fotoğraf paketleri." },
					{ icon: "🏢", title: "Çalış Daire & Apart", desc: "Çalış sahil şeridindeki apart ve daireler için Airbnb ve Booking uyumlu çekimler." },
					{ icon: "🏠", title: "Kayaköy & Üzümlü", desc: "Tarihi ve kırsal mülkler için otantik atmosferi yansıtan çekimler." },
				],
				faq: [
					{ q: "Fethiye için çekim ücreti nasıl hesaplanır?", a: "Bodrum bazlı çalışıyorum; Fethiye için ulaşım eklenir. Teklif görüşmesinde netleştirilir." },
					{ q: "Sanal tur hizmeti sunuyor musunuz?", a: "360° sanal tur hizmeti ayrı paket olarak sunulmaktadır." },
				],
			},
			web: {
				title: "Fethiye Web Tasarım ve Yazılım Geliştirme",
				metaDesc: "Fethiye'de profesyonel web tasarım ve yazılım. Göcek tekne kiralama, Ölüdeniz turizm ve emlak işletmeleri için SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Fethiye'nin tekne kiralama, turizm ve emlak sektörüne özel dijital çözümler. Göcek'ten dünyaya açılan web siteleri.",
				badges: ["Tekne Kiralama", "Turizm", "Göcek", "Ölüdeniz", "Çok Dilli", "SEO"],
				intro: "Fethiye, 12 Ada turu ve Göcek mavi yolculuğu sayesinde tekne kiralama sektöründe Türkiye'nin en rekabetçi pazarlarından birine sahiptir. Bu pazarda 'Fethiye boat rental', 'Blue Cruise Turkey' gibi global anahtar kelimelerde görünür olmak için profesyonel ve SEO odaklı bir web sitesi zorunludur.",
				details: "Göcek'teki yelkenli kiralamadan Ölüdeniz paraşüt turlarına, Hisarönü'ndeki tatil villa kiralamalarına kadar Fethiye'nin çeşitli turizm işletmelerine yönelik rezervasyon sistemleri, çok dilli içerik yönetimi ve arama motoru optimizasyonu hizmetleri sunuyoruz.",
				areas: [
					{ icon: "⛵", title: "Tekne & Mavi Yolculuk", desc: "Rezervasyon takvimi, online ödeme ve çok dilli içerik destekli tekne kiralama platformları." },
					{ icon: "🪂", title: "Tur & Aktivite Siteleri", desc: "Paraşüt, rafting ve doğa turu işletmeleri için rezervasyon sistemleri." },
					{ icon: "🏡", title: "Tatil Kiralık & Emlak", desc: "Airbnb bypass sistemleri ve uluslararası alıcıya yönelik emlak portalları." },
					{ icon: "🏨", title: "Otel & Butik Pansiyon", desc: "Direkt rezervasyon ve kanal yönetimiyle entegre otel web siteleri." },
				],
				faq: [
					{ q: "Fethiye'deki işletmem için SEO ne kadar sürede etki gösterir?", a: "Teknik SEO çalışmaları 1–2 ayda indekslenir. Organik sıralama kazanımı genellikle 3–6 ayda gözlemlenir." },
					{ q: "Booking.com ve Airbnb entegrasyonu yapıyor musunuz?", a: "Channel manager entegrasyonları mevcut sistemlerle (Beds24, Smoobu vb.) yapılabilir." },
				],
			},
			design: {
				title: "Fethiye Grafik Tasarım — Logo ve Kurumsal Kimlik",
				metaDesc: "Fethiye'de profesyonel grafik tasarım. Logo, kurumsal kimlik, sosyal medya ve menü tasarımı. Göcek, Hisarönü, Çalış. Cihan Duran.",
				heroDesc: "Fethiye'nin uluslararası turizm kimliğine uygun, güçlü ve akılda kalıcı marka görselliği.",
				badges: ["Logo", "Tekne Kiralama", "Turizm", "Sosyal Medya", "Menü"],
				intro: "Fethiye'de faaliyet gösteren tekne kiralama, tur operatörü, restoran veya butik pansiyon; İngilizce konuşan, deneyim odaklı bir müşteri kitlesine hitap eder. Bu kitle için güçlü görsel kimlik, sizi rakiplerden hızla ayrıştırır.",
				details: "Göcek'in lüks yatçı pazarından Hisarönü'nün genç turist kitlesine kadar geniş bir yelpazede marka kimliği çalışmaları yürütüyoruz. Her tasarım, hedef kitleye ve platforma göre optimize edilir.",
				areas: [
					{ icon: "⛵", title: "Tekne & Tur İşletmesi", desc: "Güvenilirlik ve macera duygusunu birleştiren logo ve kimlik tasarımları." },
					{ icon: "🍽️", title: "Restoran & Bar", desc: "Fethiye ve Hisarönü'ndeki restoran ve barlar için menü ve kimlik tasarımı." },
					{ icon: "📱", title: "Sosyal Medya Şablonları", desc: "Sezonluk Instagram ve Facebook içerik şablonları." },
					{ icon: "🖨️", title: "Tanıtım Materyalleri", desc: "Broşür, el ilanı ve tur kataloğu tasarımları." },
				],
				faq: [
					{ q: "Tekne kiralama şirketime özgü bir logo yaptırabilir miyim?", a: "Evet. Sektöre, filosunuzun tonuna ve hedef kitlenize özel konseptler hazırlanır." },
					{ q: "Sosyal medya yönetimine de destek veriyor musunuz?", a: "Tasarım şablonları ve içerik önerileri sunuyoruz, aktif yönetim hizmeti şu an mevcut değil." },
				],
			},
		},
	},

	datca: {
		name: "Datça",
		region: "Muğla",
		slug: "datca",
		lat: "36.7630",
		lng: "27.6864",
		description: "Datça Yarımadası; Ege ve Akdeniz'in buluştuğu nokta, el değmemiş koylar, organik yaşam ve sakin doğasıyla özgün bir destinasyondur.",
		services: {
			drone: {
				title: "Datça Drone Çekimi",
				metaDesc: "Datça'da profesyonel drone çekimi. Yarımada koyları, tekne, villa ve doğa fotoğrafı için hava çekimi hizmetleri. Cihan Duran.",
				heroDesc: "Ege ile Akdeniz'in buluştuğu Datça Yarımadası'nın el değmemiş koylarını, antik Knidos'u ve zeytinlikleri havadan keşfedin.",
				badges: ["Yarımada", "Koy", "Knidos", "Doğa", "Organik", "Sakinlik"],
				intro: "Datça, Türkiye'nin en az bozulmuş kıyı şeritlerinden birine sahip, yavaş turizm anlayışının temsilcisi bir destinasyondur. Bu el değmemiş coğrafya, drone çekimi için ülkedeki en çarpıcı görsel malzemeyi sunar: Hayıtbükü ve Ovabükü koyları, antik Knidos kalıntıları, balmumu renginde zeytinlikler ve iki denizin buluştuğu şapkası.",
				details: "Datça'da drone çekimi; emlak yatırımı yapan, doğa turlarını tanıtan veya organik ürünlerini pazarlamak isteyen işletmeler için eşsiz bir görsel avantaj yaratır. Yavaş turizmin anahtarı olan 'sakinlik ve doğallık' duygusunu en iyi havadan bir çekim aktarır.",
				areas: [
					{ icon: "🏖️", title: "Koy & Plaj Çekimi", desc: "Hayıtbükü, Ovabükü ve Palamutbükü gibi el değmemiş koy ve plajların havadan görüntüleri." },
					{ icon: "🏛️", title: "Antik Knidos", desc: "Datça'nın en önemli tarihi mirası Knidos antik kenti için turizm tanıtım çekimleri." },
					{ icon: "🏡", title: "Villa & Taş Ev", desc: "Datça'nın geleneksel taş evleri ve modern villalar için satış amaçlı hava çekimleri." },
					{ icon: "🫒", title: "Organik & Doğa", desc: "Zeytinlikler, badem bahçeleri ve kırsal alan çekimleri. Tarım işletmeleri için tanıtım." },
				],
				faq: [
					{ q: "Datça'ya uzaktan gelinebilir mi?", a: "Datça'ya Bodrum-Datça feribot hattı veya kara yoluyla ulaşılır. Çekim tarihi ve lojistik önceden planlanır." },
					{ q: "Knidos'ta drone çekimi yapılabilir mi?", a: "Knidos arkeolojik koruma alanıdır. Kültür Bakanlığı izni gerekmektedir. Bu süreç proje başında başlatılır." },
				],
			},
			photo: {
				title: "Datça Emlak ve Fotoğraf Çekimi",
				metaDesc: "Datça'da profesyonel emlak ve doğa fotoğrafçılığı. Taş ev, villa ve koy çekimleri. Datça Yarımadası'nın özgün atmosferini fotoğrafla yakalayın. Cihan Duran.",
				heroDesc: "Datça'nın otantik taş evlerini, koylarını ve organik yaşam alanlarını; bu atmosferi arayan alıcılara doğru aktaran profesyonel fotoğraflarla sunun.",
				badges: ["Taş Ev", "Villa", "Koy", "Organik", "Doğa", "Yarımada"],
				intro: "Datça emlak piyasasında alıcı profili çok özeldir: şehir hayatından kaçan, doğallık ve sakinlik arayan, genellikle bilinçli bir kitledir. Bu alıcılar, fotoğraflarda gerçekçiliği, organik atmosferi ve yeri görmek ister. Dubleks görsellerin değil, gerçek Datça ruhunu yansıtan fotoğrafların etkili olduğu bir pazar.",
				details: "Geleneksel taş ev dokusunun serin tonlarını, zeytinliklerin altın rengini ve Datça günbatımının pembelerini doğru ekipman ve zamanlamayla fotoğraflıyoruz. Her çekim, mülkün en güçlü özelliğini ön plana çıkaracak şekilde planlanır.",
				areas: [
					{ icon: "🪨", title: "Taş Ev & Köy Evi", desc: "Datça'ya özgü geleneksel taş evlerin özgün atmosferini yakalayan çekimler." },
					{ icon: "🏡", title: "Modern Villa", desc: "Datça'daki çağdaş villalar için satış ve kiralama ilanı çekimleri." },
					{ icon: "🌊", title: "Koy Manzaralı Mülkler", desc: "Deniz manzaralı mülklerin değerini öne çıkaran kompozisyonlar." },
					{ icon: "🫒", title: "Tarım & Organik", desc: "Zeytinlik, badem bahçesi ve organik tarım alanları için ürün ve alan fotoğrafları." },
				],
				faq: [
					{ q: "Datça'da çekim için en iyi mevsim hangisi?", a: "İlkbahar (Nisan–Mayıs) ve sonbahar (Eylül–Ekim) hem ışık hem de doğanın rengi açısından idealdir." },
					{ q: "Airbnb için de çekim yapıyor musunuz?", a: "Evet. Datça'daki kiralık mülkler için Airbnb ve Booking uyumlu paketler sunulmaktadır." },
				],
			},
			web: {
				title: "Datça Web Tasarım ve Yazılım Geliştirme",
				metaDesc: "Datça'da profesyonel web tasarım ve yazılım. Organik ürün, turizm ve pansiyon işletmeleri için SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Datça'nın özgün ve sakin kimliğini yansıtan, doğru kitleye ulaşan web siteleri. Organik ürünlerden tatil kiralamalarına dijital çözümler.",
				badges: ["Organik Ürün", "Tatil Kiralama", "Pansiyon", "Doğa Turizmi", "SEO"],
				intro: "Datça'daki işletmeler küçük ölçekli ama değer odaklı bir kitleye hitap eder. 'Datça organik badem', 'Datça tatil evi kiralama' veya 'Datça yavaş turizm' gibi arama sorgularında üst sıralarda görünmek; reklam harcaması yapmadan doğru müşteriyi çekmenin en etkili yoludur.",
				details: "Datça zeytinyağı, badem, kekik gibi organik ürünleri satan üreticilerden; doğa turları düzenleyen rehberlere; tatil evi kiralayan mülk sahiplerine kadar Datça'nın ihtiyaç duyduğu her türlü dijital çözümü sunuyoruz.",
				areas: [
					{ icon: "🫒", title: "Organik Ürün E-Ticaret", desc: "Zeytinyağı, badem, kekik ve organik ürünleri Türkiye geneline satmak için e-ticaret siteleri." },
					{ icon: "🏡", title: "Tatil Kiralık Sitesi", desc: "Airbnb bağımlılığını azaltan, direkt rezervasyon sistemli tatil evi siteleri." },
					{ icon: "🥾", title: "Doğa Turu Platformu", desc: "Yürüyüş, tekne turu ve doğa aktiviteleri için rezervasyon sistemleri." },
					{ icon: "🏨", title: "Butik Pansiyon", desc: "Küçük ölçekli konaklama tesisleri için SEO uyumlu tanıtım siteleri." },
				],
				faq: [
					{ q: "Datça'daki organik ürünlerimi online satabilir miyim?", a: "Evet. Kargo entegrasyonlu, kredi kartı destekli e-ticaret siteleri kurulabilir." },
					{ q: "Küçük bir pansiyon için web sitesi yaptırmaya değer mi?", a: "Evet. Booking komisyonunu bypass eden bir direkt rezervasyon sitesi kısa sürede kendini amorti eder." },
				],
			},
			design: {
				title: "Datça Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Datça'da profesyonel grafik tasarım. Organik ürün, pansiyon ve doğa turizmi işletmeleri için logo ve kurumsal kimlik. Cihan Duran.",
				heroDesc: "Datça'nın doğallık ve özgünlük değerlerini yansıtan, hedef kitlenizle rezonans kuran marka tasarımları.",
				badges: ["Logo", "Organik Marka", "Ambalaj", "Pansiyon", "Doğa Turizmi"],
				intro: "Datça'da organik ürün, tatil evi veya doğa turizmi işletiyorsanız markanızın görsel dili doğallık, sadelik ve özgünlük üzerine kurulmalıdır. Bu değerleri doğru aktaran bir logo ve kimlik, hedef kitlenizde anında güven oluşturur.",
				details: "Datça zeytinyağı ambalajından pansiyon logosuna, doğa turu markasından el sanatları girişimine kadar Datça ruhuna uygun tasarımlar üretiyoruz. Minimalist, doğa tonları ve el yapımı estetik ön planda.",
				areas: [
					{ icon: "🫒", title: "Organik Ürün & Ambalaj", desc: "Zeytinyağı, badem ezmesi ve organik ürünler için raf etkisi yaratan ambalaj tasarımları." },
					{ icon: "✏️", title: "Logo & Kimlik", desc: "Pansiyon, tatil evi ve doğa turu işletmeleri için sade ve akılda kalıcı logo." },
					{ icon: "🌿", title: "Sürdürülebilir Tasarım", desc: "Ekolojik değerlerle örtüşen, doğal malzeme estetiğini yansıtan görsel kimlikler." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Datça atmosferini aktaran Instagram içerik şablonları." },
				],
				faq: [
					{ q: "Organik ürün ambalajı için baskıya hazır dosya alabilir miyim?", a: "Evet. CMYK, baskı çözünürlüğünde tüm dosyalar teslim edilir." },
					{ q: "Datça'da yüz yüze görüşme yapabilir miyiz?", a: "Bodrum merkezli çalışıyorum; proje başında görüntülü görüşme veya gerektiğinde ziyaret düzenlenebilir." },
				],
			},
		},
	},

	yalikavak: {
		name: "Yalıkavak",
		region: "Bodrum",
		slug: "yalikavak",
		lat: "37.1126",
		lng: "27.2910",
		description: "Yalıkavak, Türkiye'nin en prestijli marinasına, mega yat sezonuna ve lüks villa bölgelerine ev sahipliği yapan Bodrum'un en değerli ilçesidir.",
		services: {
			drone: {
				title: "Yalıkavak Drone Çekimi",
				metaDesc: "Yalıkavak'ta profesyonel drone çekimi. D-Marin Yalıkavak, mega yat, lüks villa ve marina için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "D-Marin Yalıkavak'taki mega yatları, Bodrum yarımadasının en lüks villalarını ve turkuaz koyları havadan görüntüleyin.",
				badges: ["D-Marin", "Mega Yat", "Lüks Villa", "Marina", "Bodrum", "4K"],
				intro: "Yalıkavak Marinası, her yaz dünyaca ünlü süper yatları ve mega yatları ağırlayan Türkiye'nin en prestijli denizcilik noktasıdır. Bu pazarda bir yat veya villanın drone ile çekilmesi, standart ilanın çok ötesinde bir etki yaratır.",
				details: "Yalıkavak tepelerinden koya inen lüks villalar, marinadan yükselen karmaşık yelken direği silüetleri ve açık denizde gün batımına karşı hareket eden mega yatlar — tüm bunları bir arada yakalayabilecek tek yöntem profesyonel hava çekimidir.",
				areas: [
					{ icon: "🛥️", title: "Mega Yat & Marina", desc: "D-Marin Yalıkavak'taki süper ve mega yatlar için uluslararası standartlarda tanıtım çekimleri." },
					{ icon: "🏡", title: "Lüks Villa & Rezidans", desc: "Yalıkavak tepelerindeki villa ve rezidanslar için satış ve kiralama amaçlı hava çekimleri." },
					{ icon: "🌅", title: "Gün Batımı & Altın Saat", desc: "Yalıkavak'ın ünlü gün batımlarını yakalayan özel zamanlı drone çekimleri." },
					{ icon: "🏨", title: "Butik Otel & Resort", desc: "Yalıkavak'taki butik oteller için pazarlama amaçlı profesyonel hava videoları." },
				],
				faq: [
					{ q: "Yalıkavak Marina içinde drone çekimi yapılabilir mi?", a: "Marina sahası özel mülk olduğundan izin gerekmektedir. Bu izin süreci bizim tarafımızdan yönetilir." },
					{ q: "Mega yat çekimi için özel paket var mı?", a: "Evet. Yat boyutuna ve çekim süresine göre özel paketler hazırlanmaktadır." },
				],
			},
			photo: {
				title: "Yalıkavak Emlak ve Yat Fotoğraf Çekimi",
				metaDesc: "Yalıkavak'ta profesyonel emlak ve yat fotoğrafçılığı. Lüks villa, mega yat ve marina için üst segment çekim paketleri. Cihan Duran.",
				heroDesc: "Yalıkavak'taki lüks villanızı veya marinadaki yatınızı, uluslararası alıcıya hitap eden üst segment görüntülerle sunun.",
				badges: ["Lüks Villa", "Yat", "Marina", "Airbnb", "Satılık", "Kiralık"],
				intro: "Yalıkavak emlak ve yat piyasası Türkiye'nin en pahalı ve en uluslararası segmentlerinden biridir. Bu pazarda Avrupalı ve Körfez ülkelerinden alıcılar çekim kalitesini doğrudan mülk kalitesiyle ilişkilendirir.",
				details: "Geniş açı mercekler, tavan yüksekliklerini hissettiren kompozisyonlar, altın saat dış cephe çekimleri ve havuz-deniz yansımalarını yakalayan kareler — Yalıkavak'taki üst segment mülkler için özel çekim planlaması yapıyoruz.",
				areas: [
					{ icon: "🏡", title: "Lüks Villa", desc: "Satılık ve kiralık lüks villalar için uluslararası portföy çekimleri." },
					{ icon: "🛥️", title: "Yat & Tekne", desc: "Marina'daki motor yatlar, yelkenliler ve guletler için profesyonel fotoğraf ve video." },
					{ icon: "🏊", title: "Havuzlu Mülkler", desc: "Havuz, teras ve deniz manzarasını birleştiren kompozisyon odaklı çekimler." },
					{ icon: "🏠", title: "Airbnb & Kısa Dönem", desc: "Platform bazlı optimize, yüksek dönüşümlü kiralık çekim paketleri." },
				],
				faq: [
					{ q: "Yabancı alıcılar için İngilizce fotoğraf alt yazıları hazırlıyor musunuz?", a: "Evet. Uluslararası portföy için İngilizce açıklama ve meta veri desteği sunulabilir." },
					{ q: "Yalıkavak'ta çekim için en uygun saat nedir?", a: "Sabah erken saatler ve gün batımı öncesi 1-2 saat en iyi doğal ışığı verir." },
				],
			},
			web: {
				title: "Yalıkavak Web Tasarım ve Yazılım Geliştirme",
				metaDesc: "Yalıkavak'ta profesyonel web tasarım ve yazılım. Marina işletmeleri, lüks villa kiralama ve yat charter için SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Yalıkavak'ın lüks segmentine hitap eden, uluslararası standartlarda ve çok dilli web sitesi çözümleri.",
				badges: ["Yat Charter", "Lüks Kiralama", "Marina", "Çok Dilli", "SEO", "E-Ticaret"],
				intro: "'Yalıkavak luxury villa rental', 'yacht charter Bodrum Yalikavak' gibi yüksek değerli anahtar kelimelerde Google'ın ilk sayfasında yer almak; yıllık milyonlarca liralık kiralama ve satış gelirine doğrudan etki eden bir yatırımdır.",
				details: "Yalıkavak'taki yat kiralama şirketleri, butik otel ve villa kiralama işletmeleri için İngilizce, Almanca ve Arapça dil destekli, online ödeme entegrasyonlu ve Google oteller/rezervasyon sistemleriyle uyumlu web platformları geliştiriyoruz.",
				areas: [
					{ icon: "🛥️", title: "Yat Charter Sitesi", desc: "Çevrimiçi rezervasyon, takvim yönetimi ve ödeme entegrasyonlu yat kiralama platformu." },
					{ icon: "🏡", title: "Villa Kiralama", desc: "Direkt rezervasyonu teşvik eden, Airbnb ve Booking komisyonunu bypass eden kiralama siteleri." },
					{ icon: "🛍️", title: "Marina İşletmesi", desc: "Deniz sporları, transfer ve liman hizmetleri işletmeleri için kurumsal web siteleri." },
					{ icon: "💎", title: "Lüks Segment Tasarım", desc: "Hedef kitlenin beklediği premium görsel dil ve kullanıcı deneyimiyle tasarım." },
				],
				faq: [
					{ q: "Yalıkavak için hangi dillerde web sitesi yapıyorsunuz?", a: "Türkçe, İngilizce, Almanca ve Arapça destekli siteler yapılabilmektedir." },
					{ q: "Mevcut bir siteyi Yalıkavak SEO için optimize edebilir misiniz?", a: "Evet. Mevcut site analizi ve lokal SEO optimizasyonu ayrı paket olarak sunulmaktadır." },
				],
			},
			design: {
				title: "Yalıkavak Grafik Tasarım — Logo ve Kurumsal Kimlik",
				metaDesc: "Yalıkavak'ta profesyonel grafik tasarım. Marina işletmesi, yat charter ve lüks villa için logo ve kurumsal kimlik tasarımı. Cihan Duran.",
				heroDesc: "Yalıkavak'ın premium segmentinde markanızı güçlü kılacak, uluslararası estetikte logo ve kurumsal kimlik tasarımları.",
				badges: ["Logo", "Lüks Marka", "Yat Charter", "Kurumsal", "Baskı", "Sosyal Medya"],
				intro: "Yalıkavak'ta faaliyet gösteren bir yat charter, boutique otel veya lüks villa kiralama işletmesinin markası; hedef kitlesinin estetik beklentisini karşılamak zorundadır. Birinci sınıf bir marka kimliği, premium fiyatlandırmayı meşrulaştırır.",
				details: "Minimalist, zarif ve zamansız bir estetik anlayışla tasarlanan logolar ve kurumsal kimlikler; dijital platformlardan baskı materyallerine kadar tutarlı bir marka dili oluşturur.",
				areas: [
					{ icon: "⚓", title: "Marina & Yat İşletmesi", desc: "Denizcilik sektörüne özgü güçlü ve prestijli logo tasarımları." },
					{ icon: "🏡", title: "Lüks Kiralama Markası", desc: "Üst segment villa ve yat kiralama işletmeleri için premium kimlik çalışmaları." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Instagram ve dijital kanallarda tutarlı ve çekici içerik şablonları." },
					{ icon: "🖨️", title: "Baskı & Kurumsal", desc: "Kartvizit, broşür, kaptan manifesto ve kurumsal baskı materyalleri." },
				],
				faq: [
					{ q: "Uluslararası pazara uygun logo nasıl olmalı?", a: "Sade, okunabilir ve kültürel yük taşımayan evrensel bir tasarım dili önerilir. Birlikte netleştiririz." },
					{ q: "Marka kimliği paketi neler içeriyor?", a: "Logo, renk paleti, tipografi, kartvizit ve temel kullanım kılavuzu standart pakete dahildir." },
				],
			},
		},
	},

	turgutreis: {
		name: "Turgutreis",
		region: "Bodrum",
		slug: "turgutreis",
		lat: "37.0167",
		lng: "27.2644",
		description: "Turgutreis, Bodrum yarımadasının batı ucunda, İngiliz expat topluluğu ve uygun fiyatlı tatil anlayışıyla öne çıkan büyük bir ilçe merkezidir.",
		services: {
			drone: {
				title: "Turgutreis Drone Çekimi",
				metaDesc: "Turgutreis'te profesyonel drone çekimi. Sahil, villa, tekne ve Bodrum batı kıyısı için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Turgutreis'in geniş sahil şeridini, rüzgarlı koyu ve Kos Adası'na uzanan manzarayı havadan görüntüleyin.",
				badges: ["Sahil", "Kos Adası", "Villa", "Tekne", "Rüzgar", "Gün Batımı"],
				intro: "Turgutreis, Bodrum'un en uzun sahil şeritlerinden birine sahip ve Yunan adaları manzarasıyla benzersiz bir coğrafyada konumlanmaktadır. Bu geniş coğrafyayı ve deniz yatağını ancak havadan çekim tam olarak aktarabilir.",
				details: "Turgutreis'teki tatil siteleri, villa kompleksleri, sahil apart otelleri ve marina bölgesinin tamamını kapsayan hava çekimleri; emlak satışından otel tanıtımına her alanda fark yaratır.",
				areas: [
					{ icon: "🌊", title: "Sahil & Kıyı", desc: "Turgutreis'in geniş sahil şeridi ve plajlarının havadan görüntüleri." },
					{ icon: "🏡", title: "Villa & Tatil Sitesi", desc: "Sahile yakın villa ve tatil sitelerinin satış amaçlı hava çekimleri." },
					{ icon: "⛵", title: "Tekne & Marina", desc: "Turgutreis marinasındaki tekneler için tanıtım çekimleri." },
					{ icon: "🌅", title: "Gün Batımı Çekimi", desc: "Türkiye'nin en güzel gün batımlarından birinin yaşandığı Turgutreis'te özel gün batımı çekimleri." },
				],
				faq: [
					{ q: "Turgutreis sahilinde drone çekimi serbest mi?", a: "Sahil bölgeleri için SHGM kuralları geçerlidir. Kısıtlamaları önceden kontrol ederek izin alıyoruz." },
					{ q: "Bodrum'dan Turgutreis'e geliniz mi?", a: "Evet, Turgutreis Bodrum'a yaklaşık 18 km mesafededir. Ulaşım ücrete dahildir." },
				],
			},
			photo: {
				title: "Turgutreis Emlak ve Fotoğraf Çekimi",
				metaDesc: "Turgutreis'te profesyonel emlak fotoğrafçılığı. Villa, daire ve apart otel için fotoğraf ve video çekimi. Bodrum batı kıyısı. Cihan Duran.",
				heroDesc: "Turgutreis'teki mülkünüzü, hedef kitlenizin beklentisine uygun profesyonel görüntülerle satışa veya kiralamaya hazırlayın.",
				badges: ["Villa", "Apart", "Sahil", "Airbnb", "Sahibinden", "Bodrum"],
				intro: "Turgutreis emlak piyasası özellikle İngiliz ve Alman alıcıların ilgi gösterdiği, orta-üst segment mülklerin yoğun olduğu bir alandır. Bu kitle çevrimi çevrimiçi inceler ve fotoğraf kalitesi karar sürecinde belirleyicidir.",
				details: "Apart otellerden müstakil villalara, sahil kenarı konutlardan tatil sitesi dairelerine kadar Turgutreis'in tüm mülk tiplerinde profesyonel çekim hizmeti sunuyoruz.",
				areas: [
					{ icon: "🏡", title: "Villa & Müstakil", desc: "Turgutreis ve çevresindeki villaların satış ve uzun dönem kiralama çekimleri." },
					{ icon: "🏢", title: "Apart & Daire", desc: "Tatil apart daireleri için Airbnb ve Sahibinden platformuna uygun çekimler." },
					{ icon: "🏨", title: "Apart Otel", desc: "Turgutreis'teki apart oteller için sezonluk tanıtım fotoğraf paketleri." },
					{ icon: "🌊", title: "Deniz Manzaralı", desc: "Deniz manzarasının değeri artırdığı mülkler için kompozisyon odaklı çekimler." },
				],
				faq: [
					{ q: "Turgutreis'te çekim için ne kadar önceden randevu almalıyım?", a: "Yaz sezonu için en az 1 hafta, sezon dışı için 2-3 gün yeterlidir." },
					{ q: "Hem iç hem dış mekan çekimi yapıyor musunuz?", a: "Evet. Standart paketlere iç mekan, dış cephe ve bahçe çekimi dahildir." },
				],
			},
			web: {
				title: "Turgutreis Web Tasarım ve Yazılım Geliştirme",
				metaDesc: "Turgutreis'te profesyonel web tasarım. Apart otel, villa kiralama ve emlak işletmeleri için SEO uyumlu web siteleri. Bodrum batısı. Cihan Duran.",
				heroDesc: "Turgutreis'teki apart otel, villa kiralama veya emlak işletmenizi dijitalde doğru konumlandırın.",
				badges: ["Apart Otel", "Villa Kiralama", "Emlak", "SEO", "İngilizce", "Bodrum"],
				intro: "Turgutreis'te konaklama veya emlak işletiyorsanız, özellikle İngiliz pazarına yönelik İngilizce içerik ve 'Turgutreis holiday apartments', 'Turgutreis property for sale' gibi anahtar kelimelerde görünürlük kazanmak kritik önem taşır.",
				details: "Turgutreis'teki apart otel, tatil kiralık villa ve emlak ofislerine yönelik; rezervasyon sistemi, çok dilli içerik ve lokal SEO altyapısı entegre edilmiş web sitesi çözümleri sunuyoruz.",
				areas: [
					{ icon: "🏨", title: "Apart Otel Sitesi", desc: "Online rezervasyon ve oda yönetimi entegrasyonlu apart otel web siteleri." },
					{ icon: "🏡", title: "Villa Kiralama", desc: "Turgutreis'teki kiralık villalar için direkt rezervasyon sistemi." },
					{ icon: "🏢", title: "Emlak Ofisi", desc: "Satılık mülklerin İngilizce ve Türkçe listelenebildiği emlak siteleri." },
					{ icon: "🌐", title: "Çok Dilli SEO", desc: "İngiliz ve Alman pazarına yönelik dil ve SEO optimizasyonu." },
				],
				faq: [
					{ q: "Turgutreis'te zaten bir web sitem var, SEO'sunu yapabilir misiniz?", a: "Evet. Mevcut site analizi, teknik SEO ve içerik optimizasyonu ayrı hizmet olarak sunulmaktadır." },
					{ q: "WhatsApp rezervasyon entegrasyonu yapabiliyor musunuz?", a: "Evet. WhatsApp Business API veya basit yönlendirme entegrasyonu yapılabilir." },
				],
			},
			design: {
				title: "Turgutreis Grafik Tasarım — Logo ve Kurumsal Kimlik",
				metaDesc: "Turgutreis'te profesyonel grafik tasarım. Apart otel, villa kiralama ve turizm işletmeleri için logo ve kurumsal kimlik. Cihan Duran.",
				heroDesc: "Turgutreis'teki işletmeniz için güçlü, akılda kalıcı ve uluslararası pazara hitap eden marka kimliği tasarımları.",
				badges: ["Logo", "Apart Otel", "Turizm", "Sosyal Medya", "Baskı", "İngilizce"],
				intro: "Turgutreis'te yoğun İngiliz turist kitlesine hizmet eden işletmelerin markası hem Türkçe hem İngilizce konuşan kitlelere hitap etmelidir. Doğru bir logo ve kimlik, uluslararası güven inşa eder.",
				details: "Apart otellerden tatil kiralık platformlarına, yerel işletmelerden restoranlardan dükkan tabelalarına kadar Turgutreis pazarına uygun tasarım çözümleri üretiyoruz.",
				areas: [
					{ icon: "🏨", title: "Apart Otel & Pansiyon", desc: "Uluslararası misafirlere hitap eden konaklama markaları için logo ve kimlik." },
					{ icon: "🍽️", title: "Restoran & Kafe", desc: "Turgutreis'teki yeme-içme işletmeleri için menü ve marka tasarımı." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Sezon boyunca tutarlı içerik paylaşımı için hazır şablonlar." },
					{ icon: "🖨️", title: "Tabela & Baskı", desc: "Dükkan tabelası, broşür ve tanıtım materyalleri." },
				],
				faq: [
					{ q: "Apart otelim için kaç günde logo hazırlanır?", a: "Standart logo paketi 5-7 iş günü, hızlı paket 2-3 iş günüdür." },
					{ q: "İngilizce slogan veya isim önerisinde bulunuyor musunuz?", a: "Evet. Marka isimlendirme ve slogan desteği tasarım danışmanlığı kapsamında sunulabilir." },
				],
			},
		},
	},

	golturkbuku: {
		name: "Göltürkbükü",
		region: "Bodrum",
		slug: "golturkbuku",
		lat: "37.0939",
		lng: "27.4044",
		description: "Göltürkbükü (Gölköy + Türkbükü), Bodrum'un en seçkin tatil destinasyonu; plaj kulüpleri, ünlü ziyaretçiler ve lüks atmosferiyle Türkiye'nin St. Tropez'i olarak bilinir.",
		services: {
			drone: {
				title: "Göltürkbükü Drone Çekimi",
				metaDesc: "Göltürkbükü'nde profesyonel drone çekimi. Lüks villa, plaj kulübü ve Bodrum'un en prestijli koyu için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Türkiye'nin St. Tropez'inin eşsiz koyunu, lüks villalarını ve plaj kulüplerini havadan görüntüleyin.",
				badges: ["Türkbükü", "Gölköy", "Lüks", "Plaj Kulübü", "Villa", "4K"],
				intro: "Göltürkbükü, Türkiye'nin en seçkin tatil bölgesi olarak her yaz üst gelir grubunu, ünlüleri ve uluslararası yatçıları ağırlar. Bu segmentte bir villa veya plaj kulübünün tanıtımı, görsel kaliteyle doğru orantılıdır.",
				details: "Gölköy ve Türkbükü koylarının oluşturduğu doğal körfez yapısı, iki yakadan yükselen lüks villalar ve yoğun yaz sezonunda marinaya sıkışan yatlar — bu tabloyu en iyi havadan bir drone çekimi aktarır.",
				areas: [
					{ icon: "🏖️", title: "Plaj Kulübü", desc: "Göltürkbükü'nün ünlü plaj kulüpleri için tanıtım ve sosyal medya içerik çekimleri." },
					{ icon: "🏡", title: "Lüks Villa", desc: "Korunaklı siteler ve denize sıfır villaların satış ve kiralama portföy çekimleri." },
					{ icon: "🛥️", title: "Yat & Tekne", desc: "Göltürkbükü'nde demirleyen yatlar için tanıtım ve charter pazarlama çekimleri." },
					{ icon: "🌊", title: "Koy & Doğa", desc: "Gölköy ve Türkbükü koylarının bütününü yakalayan geniş alan çekimleri." },
				],
				faq: [
					{ q: "Göltürkbükü'nde özel mülk üzerinde drone çekimi yapılabilir mi?", a: "Özel mülk sahibinin izniyle yapılabilir. Çekim planlamasında bunu birlikte organize ediyoruz." },
					{ q: "Plaj kulübü sosyal medya içerikleri için çekim yapıyor musunuz?", a: "Evet. Sezonluk sosyal medya içerik paketleri mevcuttur." },
				],
			},
			photo: {
				title: "Göltürkbükü Emlak ve Fotoğraf Çekimi",
				metaDesc: "Göltürkbükü'nde profesyonel emlak fotoğrafçılığı. Lüks villa, denize sıfır mülk ve plaj kulübü için üst segment çekim. Cihan Duran.",
				heroDesc: "Göltürkbükü'ndeki lüks villanızı veya mülkünüzü, bu segmentin beklediği görsel kaliteyle pazara sunun.",
				badges: ["Lüks Villa", "Denize Sıfır", "Türkbükü", "Gölköy", "Kiralık", "Satılık"],
				intro: "Göltürkbükü emlak piyasasında alıcı profili son derece seçkin ve görsel zevki yüksektir. Mülkün gerçek değerini yansıtan kaliteli görseller, fiyat pazarlıklarını minimuma indirger.",
				details: "Sabah erken saatin yumuşak ışığında veya gün batımının altın tonlarında; havuz yansımaları, deniz manzaralı teraslar ve gizlilik içindeki bahçe alanlarıyla Göltürkbükü'nün lüks ruhunu fotoğraflıyoruz.",
				areas: [
					{ icon: "💎", title: "Üst Segment Villa", desc: "Göltürkbükü'nün en değerli mülkleri için uluslararası portföy çekimleri." },
					{ icon: "🏊", title: "Havuz & Teras", desc: "Sonsuzluk havuzu, deniz manzaralı teras ve açık yaşam alanı çekimleri." },
					{ icon: "🏖️", title: "Plaj & Özel İskele", desc: "Özel plaj ve iskeleye sahip mülkler için bu avantajı öne çıkaran çekimler." },
					{ icon: "🏠", title: "Kısa Dönem Kiralık", desc: "Sezonluk kiralık mülkler için yüksek dönüşümlü platform çekimleri." },
				],
				faq: [
					{ q: "Göltürkbükü'nde çekim için hangi saatler önerilir?", a: "Sabah 07:00-09:00 arası ve gün batımından 1 saat önce en ideal ışık koşulları yaşanır." },
					{ q: "Sanal tur veya 360° çekim yapıyor musunuz?", a: "Evet. Lüks villa satışları için 360° sanal tur hizmeti mevcuttur." },
				],
			},
			web: {
				title: "Göltürkbükü Web Tasarım ve Yazılım",
				metaDesc: "Göltürkbükü'nde profesyonel web tasarım. Lüks villa kiralama, plaj kulübü ve butik otel için SEO uyumlu premium web siteleri. Cihan Duran.",
				heroDesc: "Göltürkbükü'nün premium pazarına uygun, lüks estetikte ve yüksek performanslı web sitesi çözümleri.",
				badges: ["Lüks Kiralama", "Plaj Kulübü", "Butik Otel", "Premium", "SEO", "Çok Dilli"],
				intro: "'Göltürkbükü villa kiralama', 'Türkbükü luxury accommodation' gibi arama sorgularında üst sıralarda yer almak, doğru ve ödeme gücü yüksek kitleyi çekmenin en etkili yoludur.",
				details: "Göltürkbükü'ndeki lüks kiralama, plaj kulübü ve boutique otel işletmeleri için; premium tasarım dili, çok dilli içerik ve online rezervasyon sistemi entegre edilmiş web platformları geliştiriyoruz.",
				areas: [
					{ icon: "💎", title: "Lüks Villa Kiralama", desc: "Özel havuzlu villaların kişiye özel rezervasyon süreçleri için premium dijital platform." },
					{ icon: "🏖️", title: "Plaj Kulübü", desc: "Masa rezervasyonu, etkinlik takvimi ve sosyal medya entegrasyonlu plaj kulübü siteleri." },
					{ icon: "🏨", title: "Butik Otel", desc: "Booking bypass sistemi, doğrudan rezervasyon ve CRM entegrasyonlu otel siteleri." },
					{ icon: "🌐", title: "Premium Tasarım", desc: "Hedef kitlenin beklediği lüks estetikte, yavaş ve şık kullanıcı deneyimi." },
				],
				faq: [
					{ q: "Plaj kulübü için online masa rezervasyonu sistemi yapılabilir mi?", a: "Evet. Tarih-saat bazlı masa rezervasyon sistemi geliştirilebilir." },
					{ q: "Göltürkbükü için hangi dil desteği öneriyorsunuz?", a: "Türkçe ve İngilizce zorunlu; hedef kitleye göre Arapça veya Rusça da eklenebilir." },
				],
			},
			design: {
				title: "Göltürkbükü Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Göltürkbükü'nde profesyonel grafik tasarım. Lüks villa, plaj kulübü ve butik otel için premium logo ve marka kimliği. Cihan Duran.",
				heroDesc: "Göltürkbükü'nün seçkin atmosferine uygun, lüks ve zamansız marka kimliği tasarımları.",
				badges: ["Logo", "Premium Marka", "Plaj Kulübü", "Butik Otel", "Lüks"],
				intro: "Göltürkbükü'nde faaliyet gösteren bir işletmenin markası, müşterisinin sahip olduğu estetiği ve yaşam standardını yansıtmak zorundadır. Bu segmentte görsel kimlik, fiyatlandırmayı doğrular.",
				details: "Minimalizm, zarafet ve özgünlük odaklı tasarım anlayışıyla; plaj kulübünden lüks kiralama markasına kadar Göltürkbükü ruhuna uygun kimlikler oluşturuyoruz.",
				areas: [
					{ icon: "🏖️", title: "Plaj Kulübü Markası", desc: "Özgün, premium ve sosyal medyada güçlü etkisi olan plaj kulübü kimlikleri." },
					{ icon: "💎", title: "Lüks Kiralama Markası", desc: "Villa ve kiralama işletmeleri için zamansız ve uluslararası estetikte logo." },
					{ icon: "🍾", title: "Yeme-İçme & Eğlence", desc: "Restoran, bar ve eğlence mekanları için ortamla uyumlu kimlik tasarımları." },
					{ icon: "📱", title: "Dijital İçerik", desc: "Instagram ve dijital kanallarda marka tutarlılığı için içerik şablonları." },
				],
				faq: [
					{ q: "Plaj kulübü için özgün bir marka ismi önerir misiniz?", a: "Evet. Marka isimlendirme ve konsept geliştirme danışmanlığı hizmetimiz mevcuttur." },
					{ q: "Tasarımlar baskıya hazır formatta mı teslim ediliyor?", a: "Evet. CMYK ve RGB dahil tüm formatlarda teslim edilir." },
				],
			},
		},
	},

	gundogan: {
		name: "Gündoğan",
		region: "Bodrum",
		slug: "gundogan",
		lat: "37.1256",
		lng: "27.3839",
		description: "Gündoğan, Bodrum yarımadasının kuzeyinde sakin koyu, doğal güzelliği ve hızla değerlenen emlak piyasasıyla öne çıkan, henüz keşfedilmekte olan bir destinasyondur.",
		services: {
			drone: {
				title: "Gündoğan Drone Çekimi",
				metaDesc: "Gündoğan'da profesyonel drone çekimi. Sakin koy, villa ve Bodrum kuzeyi için hava fotoğrafı ve 4K video hizmetleri. Cihan Duran.",
				heroDesc: "Gündoğan'ın sakin koyunu, el değmemiş doğasını ve hızla gelişen yapılaşmasını havadan görüntüleyin.",
				badges: ["Sakin Koy", "Doğa", "Villa", "Yatırım", "Bodrum", "4K"],
				intro: "Gündoğan, Göltürkbükü ile Yalıkavak arasında konumlanan, sakin yapısı ve doğal koyuyla hızla değer kazanan bir Bodrum destinasyonudur. Bu organik büyüme, emlak yatırımcısının ilgisini çeken benzersiz bir fırsatı temsil eder.",
				details: "Gündoğan'daki yeni villa projelerinin, zeytinliklerle çevrili arazilerin ve koy çevresindeki mülklerin profesyonel drone çekimi; bölgenin yükselen değerini potansiyel alıcılara en etkileyici biçimde iletir.",
				areas: [
					{ icon: "🌊", title: "Gündoğan Koyu", desc: "Gündoğan'ın doğal koyunun ve kıyı şeridinin havadan görüntüleri." },
					{ icon: "🏡", title: "Villa & Arazi", desc: "Yeni inşaat ve proje aşamasındaki villalar ile arsalar için çekim." },
					{ icon: "🫒", title: "Doğa & Zeytinlik", desc: "Bölgenin özgün peyzajını tanıtan turizm ve yatırım çekimleri." },
					{ icon: "🏗️", title: "İnşaat & Proje", desc: "Yatırımcılara proje ilerlemesini aktaran periyodik drone çekimleri." },
				],
				faq: [
					{ q: "Gündoğan'da drone çekimi ne kadar sürer?", a: "Standart bir mülk çekimi 1-2 saat, kapsamlı alan çekimleri yarım güne kadar sürebilir." },
					{ q: "Proje süreci boyunca periyodik çekim hizmeti var mı?", a: "Evet. İnşaat sürecini belgelemek için aylık veya dönümlük çekim paketleri sunulmaktadır." },
				],
			},
			photo: {
				title: "Gündoğan Emlak ve Fotoğraf Çekimi",
				metaDesc: "Gündoğan'da profesyonel emlak fotoğrafçılığı. Villa, arazi ve tatil evi için fotoğraf ve video çekimi. Bodrum kuzeyi. Cihan Duran.",
				heroDesc: "Gündoğan'daki mülkünüzü yatırımcılara ve tatil arayan alıcılara cazip kılacak profesyonel fotoğraflarla sunun.",
				badges: ["Villa", "Arazi", "Koy Manzaralı", "Yatırım", "Tatil", "Airbnb"],
				intro: "Gündoğan'ın henüz erken aşamadaki emlak piyasasında doğru fotoğraflama, mülkün değerini tam olarak aktarabilecek yegane araçtır. Erken alıcıyı yakalamak için profesyonel görsel içerik kritik önem taşır.",
				details: "Koy manzaralı teraslar, zeytinlik içindeki villalar ve doğayla iç içe geçmiş peyzajların en değerli açılarını yakalayan profesyonel çekimler sunuyoruz.",
				areas: [
					{ icon: "🏡", title: "Villa & Müstakil", desc: "Gündoğan'daki villalar için satış ve uzun dönem kiralama çekimleri." },
					{ icon: "🌿", title: "Arazi & Peyzaj", desc: "Yatırım amaçlı arsalar için konumu aktaran fotoğraflar." },
					{ icon: "🌊", title: "Koy Manzaralı", desc: "Deniz veya koy manzarasının öne çıkarıldığı değer artışı odaklı çekimler." },
					{ icon: "🏠", title: "Tatil Kiralık", desc: "Gündoğan'daki tatil evi ve apart için Airbnb uyumlu çekim paketleri." },
				],
				faq: [
					{ q: "Gündoğan'da koy manzarası olan mülkleri nasıl çekiyorsunuz?", a: "Koy manzarasını en iyi aktaran açıyı sabah veya akşam ışığında yakalayacak şekilde planlıyoruz." },
					{ q: "Arazi çekimlerinde sınır ve boyutu gösterebiliyor musunuz?", a: "Drone çekimiyle arazi sınırları ve büyüklük en net şekilde aktarılır. Harita katmanı da eklenebilir." },
				],
			},
			web: {
				title: "Gündoğan Web Tasarım ve Yazılım",
				metaDesc: "Gündoğan'da profesyonel web tasarım. Villa kiralama, emlak ve turizm işletmeleri için SEO uyumlu web siteleri. Bodrum kuzeyi. Cihan Duran.",
				heroDesc: "Gündoğan'ın yükselen değerinden faydalanın — doğru dijital varlıkla doğru alıcı ve kiracıya ulaşın.",
				badges: ["Villa Kiralama", "Emlak", "SEO", "Bodrum", "Yatırım", "Tatil"],
				intro: "'Gündoğan villa kiralama', 'Gündoğan satılık villa' aramalarında üst sıralarda yer almak; bölgeye özgü düşük rekabet ortamında görece hızlı sonuç almanızı sağlar.",
				details: "Gündoğan'daki tatil kiralık mülkler, emlak yatırımcılarına yönelik siteler ve küçük işletmeler için uygun maliyetli ve etkili web çözümleri geliştiriyoruz.",
				areas: [
					{ icon: "🏡", title: "Villa Kiralama Sitesi", desc: "Tatilcilere yönelik, takvim ve rezervasyon sistemli kişisel villa kiralama siteleri." },
					{ icon: "🏢", title: "Emlak Tanıtım", desc: "Yatırımcıya yönelik, bölge değer analizini aktaran emlak tanıtım siteleri." },
					{ icon: "🌿", title: "Küçük İşletme", desc: "Gündoğan'daki restoran, kafe ve küçük işletmeler için uygun maliyetli web siteleri." },
					{ icon: "📊", title: "Lokal SEO", desc: "Gündoğan'a özgü anahtar kelimeler için düşük rekabetli SEO çalışması." },
				],
				faq: [
					{ q: "Gündoğan için SEO'da hızlı sonuç alınabilir mi?", a: "Gündoğan, düşük rekabetli bir anahtar kelime alanıdır. 2-3 ay içinde ilk sayfa sıralamalarına ulaşmak mümkün olabilir." },
					{ q: "Sadece bir evi kiraya vermek için web sitesi yaptırmaya değer mi?", a: "Evet. Booking.com komisyonu düşüldüğünde, direkt rezervasyon sitesi kısa sürede kendini amorti eder." },
				],
			},
			design: {
				title: "Gündoğan Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Gündoğan'da profesyonel grafik tasarım. Villa kiralama ve turizm işletmeleri için logo ve kurumsal kimlik tasarımı. Cihan Duran.",
				heroDesc: "Gündoğan'ın sakin ve doğal atmosferini yansıtan, hedef kitlenizle bağ kuran marka tasarımları.",
				badges: ["Logo", "Villa Kiralama", "Turizm", "Doğa", "Sade", "Sosyal Medya"],
				intro: "Gündoğan'da tatil evi kirayan veya küçük bir işletme yürüten kişiler için bile güçlü bir logo ve kimlik; misafirlerin güven duymasını ve tekrar tercih etmesini sağlar.",
				details: "Doğallık ve sadelik ön planda, bölgenin sakin ruhunu yansıtan tasarım çözümleri üretiyoruz. Küçük bütçeli projeler için de uygun paketler mevcuttur.",
				areas: [
					{ icon: "🏡", title: "Villa & Ev Kiralaması", desc: "Tatil evi kiralaması için güven veren, sade ve akılda kalıcı logo." },
					{ icon: "🌿", title: "Doğa & Eko", desc: "Doğa odaklı işletmeler için organik estetik marka kimlikleri." },
					{ icon: "🍽️", title: "Kafe & Restoran", desc: "Gündoğan'daki yeme-içme noktaları için menü ve kimlik tasarımı." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Bölgenin doğal güzelliğini öne çıkaran içerik şablonları." },
				],
				faq: [
					{ q: "Küçük bütçem var, yine de profesyonel logo yaptırabilir miyim?", a: "Evet. Bireysel ve küçük işletmeler için uygun ölçekli paketler mevcuttur." },
					{ q: "Logo dosyalarını hangi formatlarda teslim ediyorsunuz?", a: "SVG, PNG, PDF ve EPS formatlarında teslim edilir." },
				],
			},
		},
	},

	bitez: {
		name: "Bitez",
		region: "Bodrum",
		slug: "bitez",
		lat: "37.0289",
		lng: "27.3728",
		description: "Bitez, mandalina bahçeleri, rüzgar sörfü ve kitesurf merkeziyle öne çıkan, expat topluluğunun yoğun olduğu sakin ve yeşil bir Bodrum destinasyonudur.",
		services: {
			drone: {
				title: "Bitez Drone Çekimi",
				metaDesc: "Bitez'de profesyonel drone çekimi. Kitesurf, mandalina bahçesi, villa ve Bitez koyu için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Bitez'in turkuaz koyunu, mandalina bahçelerini, kitesurf sporcularını ve sakin sahilini havadan görüntüleyin.",
				badges: ["Kitesurf", "Mandalina", "Sahil", "Villa", "Expat", "Sakin"],
				intro: "Bitez, rüzgar sporları tutkunlarının ve Bodrum'da yerleşmek isteyen expat topluluğunun gözdesi bir destinasyondur. Bu kitleye ulaşmak için profesyonel drone görüntüleri güçlü bir pazarlama aracıdır.",
				details: "Bitez koyunun sabah sakinliği, kitesurf sporcularının dinamizmi ve mandalina bahçelerinin yeşilliğini bir arada yakalayan drone çekimleri; turizm tanıtımından emlak ilanlarına geniş bir kullanım alanı sunar.",
				areas: [
					{ icon: "🪁", title: "Kitesurf & Rüzgar Sörfü", desc: "Bitez'in rüzgar sporları festivallerini ve günlük spor aktivitelerini belgeleyen çekimler." },
					{ icon: "🍊", title: "Mandalina Bahçeleri", desc: "Bitez'in özgün yeşil dokusunu oluşturan mandalina bahçelerinin havadan görüntüleri." },
					{ icon: "🏡", title: "Villa & Mülk", desc: "Bitez'deki villa ve mülkler için satış ve kiralama amaçlı hava çekimleri." },
					{ icon: "🌊", title: "Koy & Sahil", desc: "Bitez koyunun panoramik hava görüntüleri." },
				],
				faq: [
					{ q: "Kitesurf aktivitelerini drone ile çekebilir misiniz?", a: "Evet. Spor aktivite çekimleri için özel kamera ve uçuş teknikleri kullanılmaktadır." },
					{ q: "Bitez'de çekim için rüzgarlı günler sorun yaratır mı?", a: "Kitesurf çekimleri rüzgarlı günler için idealdir. Mülk çekimleri için sakin günler tercih edilir." },
				],
			},
			photo: {
				title: "Bitez Emlak ve Fotoğraf Çekimi",
				metaDesc: "Bitez'de profesyonel emlak fotoğrafçılığı. Villa, mandalina bahçeli mülk ve tatil evi için fotoğraf çekimi. Bodrum Bitez. Cihan Duran.",
				heroDesc: "Bitez'deki villanızı veya tatil evinizi, expat ve Avrupalı alıcıların beklentisine uygun profesyonel görüntülerle sunun.",
				badges: ["Villa", "Bahçeli Mülk", "Expat", "Airbnb", "Koy Manzaralı", "Yeşil"],
				intro: "Bitez'de çok sayıda expat ve Avrupalı alıcı mülk edinmektedir. Bu kitle için fotoğraf kalitesi, görüntüleme oranlarını ve teklifleri doğrudan etkiler.",
				details: "Mandalina ağaçları arasındaki villalar, koy manzaralı teraslar ve doğayla iç içe bahçeler — Bitez mülklerinin en değerli özelliklerini ön plana çıkaran çekimler yapıyoruz.",
				areas: [
					{ icon: "🏡", title: "Villa & Bahçeli Mülk", desc: "Bitez'deki bahçeli villa ve müstakil evler için kapsamlı çekim paketleri." },
					{ icon: "🍊", title: "Bahçe & Doğa", desc: "Mandalina ve zeytin ağaçlarının peyzaj değerini öne çıkaran çekimler." },
					{ icon: "🏠", title: "Tatil Kiralık", desc: "Airbnb ve tatil platformları için yüksek tıklanma oranı sağlayan çekim paketleri." },
					{ icon: "🌊", title: "Koy Erişimli Mülkler", desc: "Koya yakın veya deniz manzaralı mülklerin avantajını vurgulayan çekimler." },
				],
				faq: [
					{ q: "Bahçedeki ağaçları da çekime dahil edebilir misiniz?", a: "Evet. Bahçe ve peyzaj çekimleri standart mülk paketine dahildir." },
					{ q: "İngilizce fotoğraf açıklamaları hazırlıyor musunuz?", a: "Evet. Expat ve yabancı alıcıya yönelik İngilizce içerik desteği sunulabilir." },
				],
			},
			web: {
				title: "Bitez Web Tasarım ve Yazılım",
				metaDesc: "Bitez'de profesyonel web tasarım. Villa kiralama, kitesurf merkezi ve expat odaklı işletmeler için İngilizce SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Bitez'deki işletmenizi Avrupalı ve expat kitleye dijitalde doğru tanıtın.",
				badges: ["Villa Kiralama", "Kitesurf", "İngilizce SEO", "Expat", "Airbnb", "Bodrum"],
				intro: "'Bitez villa rental', 'Bitez kitesurf school' gibi arama sorgularında görünür olmak, uluslararası kitleye direkt ulaşmanın en etkili yoludur.",
				details: "Bitez'deki kitesurf okulları, villa kiralama işletmeleri ve expat topluluğuna yönelik hizmet veren işletmeler için İngilizce öncelikli, lokal SEO entegrasyonlu web platformları geliştiriyoruz.",
				areas: [
					{ icon: "🪁", title: "Kitesurf & Su Sporları", desc: "Ders rezervasyonu, ekipman kiralama ve etkinlik takvimi sistemli spor okulu siteleri." },
					{ icon: "🏡", title: "Villa Kiralama", desc: "İngilizce destekli, direkt rezervasyon sistemli tatil villa siteleri." },
					{ icon: "🌿", title: "Yerel & Organik", desc: "Bitez'deki organik tarım ve yerel ürün işletmeleri için e-ticaret çözümleri." },
					{ icon: "🌐", title: "Expat Odaklı", desc: "Bitez'de yaşayan veya yerleşmeyi düşünen expatlara yönelik hizmet siteleri." },
				],
				faq: [
					{ q: "Kitesurf okulu için online ders rezervasyonu sistemi yapılabilir mi?", a: "Evet. Tarih, saat ve kişi sayısı bazlı rezervasyon sistemi geliştirilebilir." },
					{ q: "Bitez için öncelikli dil hangisi olmalı?", a: "Hedef kitleye göre İngilizce öncelikli, Türkçe destekli yapılanma önerilir." },
				],
			},
			design: {
				title: "Bitez Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Bitez'de profesyonel grafik tasarım. Kitesurf okulu, villa kiralama ve expat işletmeleri için logo ve kurumsal kimlik. Cihan Duran.",
				heroDesc: "Bitez'in canlı ve sporcu ruhunu yansıtan, uluslararası kitleye hitap eden marka tasarımları.",
				badges: ["Logo", "Kitesurf", "Spor Okulu", "Villa", "Expat", "Doğa"],
				intro: "Bitez'deki kitesurf okulunun, tatil kiralık villanın veya küçük işletmenin markası; Avrupalı ve uluslararası kitleye hitap edecek sadelikte ve enerjide olmalıdır.",
				details: "Dinamizm, özgürlük ve doğa temalarını harmanlayan tasarım anlayışıyla Bitez işletmelerine özgün ve etkili marka kimlikleri oluşturuyoruz.",
				areas: [
					{ icon: "🪁", title: "Kitesurf & Spor Markası", desc: "Enerji, hareket ve özgürlük duygularını aktaran spor okulu logo ve kimliği." },
					{ icon: "🏡", title: "Villa & Kiralama", desc: "Uluslararası alıcıya güven veren villa kiralama marka kimliği." },
					{ icon: "🍊", title: "Doğa & Organik", desc: "Bitez'in yeşil dokusundan ilham alan organik ve doğal marka tasarımları." },
					{ icon: "📱", title: "Sosyal Medya & Dijital", desc: "Uluslararası takipçi kitlesine hitap eden içerik şablonları." },
				],
				faq: [
					{ q: "Kitesurf okulum için dinamik bir logo yaptırmak istiyorum.", a: "Hareketi ve özgürlüğü yansıtan, animasyona uyarlanabilir logo konseptleri hazırlıyoruz." },
					{ q: "Tasarımlarınız sosyal medyada da kullanılabilir mi?", a: "Evet. Tüm tasarımlar dijital ve baskı kullanımına uygun formatlarda teslim edilir." },
				],
			},
		},
	},

	gumbet: {
		name: "Gümbet",
		region: "Bodrum",
		slug: "gumbet",
		lat: "37.0417",
		lng: "27.4156",
		description: "Gümbet, Bodrum'a 3 km mesafede, yoğun turist akını, deniz sporları ve aktif gece hayatıyla Bodrum yarımadasının en canlı tatil bölgelerinden biridir.",
		services: {
			drone: {
				title: "Gümbet Drone Çekimi",
				metaDesc: "Gümbet'te profesyonel drone çekimi. Sahil, otel, tatil sitesi ve Bodrum kıyısı için hava fotoğrafı ve 4K video hizmetleri. Cihan Duran.",
				heroDesc: "Gümbet'in canlı sahilini, yoğun yaz sezonunu ve Bodrum körfezine uzanan manzarayı havadan görüntüleyin.",
				badges: ["Sahil", "Otel", "Tatil Sitesi", "Bodrum", "Sezon", "4K"],
				intro: "Gümbet, yaz boyunca on binlerce turisti ağırlayan, Bodrum'un en yoğun sahil destinasyonlarından biridir. Bu kalabalık rekabet ortamında öne çıkmak için profesyonel drone görüntüleri güçlü bir araçtır.",
				details: "Otellerin havuz başlarını, sahil şeridinin canlılığını ve Bodrum körfezine uzanan panoramik görünümü havadan yakalayan çekimler; otel ve tatil sitelerinin pazarlama materyallerine büyük değer katar.",
				areas: [
					{ icon: "🏨", title: "Otel & Resort", desc: "Gümbet'teki oteller için yaz sezonu pazarlama çekimleri." },
					{ icon: "🏖️", title: "Sahil & Plaj", desc: "Gümbet sahilinin canlılığını aktaran turizm tanıtım çekimleri." },
					{ icon: "🏊", title: "Tatil Sitesi", desc: "Havuzlu ve bahçeli tatil sitelerinin hava çekimleri." },
					{ icon: "🌊", title: "Bodrum Körfezi", desc: "Gümbet açıklarından Bodrum körfezini kapsayan geniş alan çekimleri." },
				],
				faq: [
					{ q: "Yoğun sezonda Gümbet'te randevu ne zaman alınmalı?", a: "Yaz sezonu için en az 1-2 hafta öncesinden randevu oluşturulması önerilir." },
					{ q: "Gümbet'te sabah çekimi mi, akşam mı önerilir?", a: "Sahil çekimleri için erken sabah (turistlerin az olduğu saat) önerilir; otel çekimleri için gün batımı idealdir." },
				],
			},
			photo: {
				title: "Gümbet Emlak ve Otel Fotoğraf Çekimi",
				metaDesc: "Gümbet'te profesyonel emlak ve otel fotoğrafçılığı. Tatil apart, otel odası ve sahil mülkleri için fotoğraf ve video çekimi. Cihan Duran.",
				heroDesc: "Gümbet'teki otel odanızı, tatil apart dairenizi veya sahil mülkünüzü doluluk oranınızı artıracak görüntülerle sunun.",
				badges: ["Apart Otel", "Otel Odası", "Sahil", "Airbnb", "Tatil", "Sezon"],
				intro: "Gümbet'te tatil amaçlı kiralık mülk veya otel işletmeciliği yapıyorsanız, fotoğraf kalitesi Booking.com ve Airbnb sıralamanızı ve doluluk oranınızı doğrudan etkiler.",
				details: "Otel lobi ve odalarından havuz alanlarına, apart dairelerden sahil kenarı işyerlerine kadar Gümbet'in her tür mülkü için profesyonel fotoğraf paketleri sunuyoruz.",
				areas: [
					{ icon: "🏨", title: "Otel Odası & Lobisi", desc: "OTA platformlarında daha yüksek tıklanma sağlayan otel iç mekan çekimleri." },
					{ icon: "🏢", title: "Apart Daire", desc: "Tatilci kitlesine yönelik, platform bazlı optimize apart daire çekimleri." },
					{ icon: "🏊", title: "Havuz & Ortak Alan", desc: "Tesisin avantajlarını öne çıkaran ortak alan ve aktivite çekimleri." },
					{ icon: "🏖️", title: "Sahil Konum", desc: "Sahile yakınlık avantajını görsel olarak aktaran dış mekan çekimleri." },
				],
				faq: [
					{ q: "Booking.com için fotoğraf boyut ve format gereksinimleri nelerdir?", a: "Tüm OTA platformlarının gereksinimi karşılayan formatlarda teslim edilir." },
					{ q: "Aynı günde hem iç hem dış mekan çekimi yapılabilir mi?", a: "Evet. Standart pakette iç mekan, dış cephe ve havuz çekimi aynı gün gerçekleştirilir." },
				],
			},
			web: {
				title: "Gümbet Web Tasarım ve Yazılım",
				metaDesc: "Gümbet'te profesyonel web tasarım. Otel, apart daire ve tatil işletmeleri için SEO uyumlu ve rezervasyon entegrasyonlu web siteleri. Cihan Duran.",
				heroDesc: "Gümbet'teki otel veya tatil kiralık işletmeniz için booking komisyonunu azaltan direkt rezervasyon siteleri.",
				badges: ["Otel", "Apart", "Rezervasyon", "SEO", "Bodrum", "Tatil"],
				intro: "Gümbet'te 'Gümbet hotel', 'Gümbet apart' gibi arama sorgularında organik görünürlük; OTA platformlarına ödenen yüksek komisyonları azaltmanın ve doğrudan gelir elde etmenin en etkili yoludur.",
				details: "Gümbet'teki otel, apart otel ve tatil sitelerine yönelik; rezervasyon motoru, oda yönetimi ve dijital pazarlama entegrasyonlu web platformları geliştiriyoruz.",
				areas: [
					{ icon: "🏨", title: "Otel Web Sitesi", desc: "Booking.com ve Airbnb'ye alternatif, direkt rezervasyonlu otel siteleri." },
					{ icon: "🏢", title: "Apart & Tatil Sitesi", desc: "Online takvim ve rezervasyon sistemi entegrasyonlu apart otel siteleri." },
					{ icon: "📊", title: "SEO & Görünürlük", desc: "Gümbet ve Bodrum anahtar kelimelerinde organik sıralama çalışması." },
					{ icon: "🔧", title: "Teknik Entegrasyon", desc: "PMS, channel manager ve ödeme sistemi entegrasyonları." },
				],
				faq: [
					{ q: "Mevcut Booking.com sayfamı direkt rezervasyon sitesiyle destekleyebilir miyim?", a: "Evet. Direkt kanal, OTA kanalını tamamlayarak komisyonsuz rezervasyon oranını artırır." },
					{ q: "Gümbet için Google Otel reklamları desteği veriyor musunuz?", a: "Google Otel entegrasyonu için teknik altyapı kurulabilir." },
				],
			},
			design: {
				title: "Gümbet Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Gümbet'te profesyonel grafik tasarım. Otel, apart ve tatil işletmeleri için logo, kurumsal kimlik ve sosyal medya tasarımı. Cihan Duran.",
				heroDesc: "Gümbet'in canlı tatil enerjisini yansıtan, tatilciyi çeken marka kimliği tasarımları.",
				badges: ["Logo", "Otel", "Apart", "Sosyal Medya", "Tatil", "Renkli"],
				intro: "Gümbet'te faaliyet gösteren bir otel veya apart işletmenin markası, enerjik, güven veren ve görsel medyada güçlü olmalıdır. Bu özellikler doğrudan doluluk oranına yansır.",
				details: "Tatil enerjisini, deniz temasını ve eğlenceyi öne çıkaran renk paletleri ve tipografi tercihleriyle Gümbet işletmelerine uygun marka kimlikleri tasarlıyoruz.",
				areas: [
					{ icon: "🏨", title: "Otel & Apart Markası", desc: "Tatilci kitleye güven ve heyecan veren otel ve apart kimlik tasarımları." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Sezonluk kampanya ve içerik şablonları." },
					{ icon: "🎨", title: "Tabela & Çevre", desc: "Otel dış cephe tabela ve yönlendirme tasarımları." },
					{ icon: "🖨️", title: "Menü & Broşür", desc: "Yeme-içme ve tesis tanıtım materyalleri." },
				],
				faq: [
					{ q: "Otelim için sezonluk sosyal medya kampanya tasarımı yapılabilir mi?", a: "Evet. Yaz sezonu, özel gün ve indirim kampanyaları için hazır şablon setleri oluşturulabilir." },
					{ q: "Logo ve sosyal medya şablonlarını birlikte yaptırabilir miyim?", a: "Evet. Logo + sosyal medya paketi daha uygun fiyatla sunulmaktadır." },
				],
			},
		},
	},

	torba: {
		name: "Torba",
		region: "Bodrum",
		slug: "torba",
		lat: "37.0744",
		lng: "27.4611",
		description: "Torba, Bodrum'a yakın sakin körfezi, lüks tatil köyleri ve marina olanaklarıyla aile tatilcilerinin ve üst segment tatilcilerin tercih ettiği huzurlu bir destinasyondur.",
		services: {
			drone: {
				title: "Torba Drone Çekimi",
				metaDesc: "Torba'da profesyonel drone çekimi. Torba körfezi, lüks tatil köyü, villa ve marina için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Torba'nın sakin körfezini, lüks tatil köylerini ve çevresindeki yeşil tepeleri havadan görüntüleyin.",
				badges: ["Torba Körfezi", "Lüks Tatil", "Villa", "Marina", "Sakin", "4K"],
				intro: "Torba, Bodrum'un gürültüsünden uzak, korunaklı körfezinde sakin bir tatil arayan üst segment tatilcilerin gözdesidir. Bu doğal güzelliği ve tesisin tam kapsamını ancak havadan çekim aktarabilir.",
				details: "Torba körfezinin korunaklı yapısı, çevresindeki ormanlık yamaçlar ve marinada demirleyen teknelerle oluşan tablo; profesyonel drone çekimi için son derece değerli bir coğrafya sunar.",
				areas: [
					{ icon: "🌊", title: "Torba Körfezi", desc: "Torba'nın korunaklı ve sakin körfezinin panoramik hava görüntüleri." },
					{ icon: "🏨", title: "Lüks Tatil Köyü", desc: "Torba'daki büyük tatil köyleri ve resort oteller için pazarlama çekimleri." },
					{ icon: "🏡", title: "Villa & Mülk", desc: "Torba'daki lüks villalar için satış ve kiralama amaçlı hava çekimleri." },
					{ icon: "⛵", title: "Marina & Tekne", desc: "Torba marinasındaki tekneler için tanıtım çekimleri." },
				],
				faq: [
					{ q: "Tatil köyü içinde drone çekimi yapabilir misiniz?", a: "Tesis yönetiminin izniyle tesis içi çekim gerçekleştirilir. Bu süreci birlikte organize ederiz." },
					{ q: "Torba için sabah mı, akşam mı daha iyi çekim verir?", a: "Körfez çekimleri için sabah sakinliği idealdir; tesis tanıtımı için gün batımı da çok etkilidir." },
				],
			},
			photo: {
				title: "Torba Emlak ve Otel Fotoğraf Çekimi",
				metaDesc: "Torba'da profesyonel emlak ve tesis fotoğrafçılığı. Lüks villa, tatil köyü ve körfez mülkleri için fotoğraf ve video çekimi. Cihan Duran.",
				heroDesc: "Torba'daki villanızı veya tesisinizi, huzurlu körfez atmosferini yansıtan profesyonel görüntülerle sunun.",
				badges: ["Lüks Villa", "Tatil Köyü", "Körfez", "Sakin", "Aile", "Airbnb"],
				intro: "Torba, aile tatilcilerinin ve huzur arayan üst segment tatilcilerin tercih ettiği bir destinasyondur. Bu kitleyi çeken görüntüler; sakinlik, doğallık ve konfor duygularını yansıtmalıdır.",
				details: "Torba'daki villa ve tatil tesislerinde sabahın erken saatlerindeki sislerin üzerinde yükselen güneşi veya körfezin akşam moruyla birleşen görüntüsünü yakalayan çekimler yapıyoruz.",
				areas: [
					{ icon: "🏡", title: "Körfez Villası", desc: "Torba körfezine bakan lüks villa ve müstakil evler için satış çekimleri." },
					{ icon: "🏨", title: "Tatil Köyü & Tesis", desc: "Büyük tatil tesislerinin tanıtım fotoğraf ve video paketleri." },
					{ icon: "🌲", title: "Doğa İçinde Mülkler", desc: "Ormanlık ve yeşil alan içindeki mülklerin doğal atmosferini aktaran çekimler." },
					{ icon: "🏠", title: "Kısa Dönem Kiralık", desc: "Torba'daki tatil evi ve apart için platform uyumlu çekim paketleri." },
				],
				faq: [
					{ q: "Torba'da körfez manzarasını en iyi hangi açıdan çekebilirsiniz?", a: "Lokasyona göre en iyi açıyı önceden keşfediyoruz. Sabah veya akşam ışığı körfez manzarasını en güzel şekilde verir." },
					{ q: "Tatil köyü için periyodik fotoğraf güncellemesi yapıyor musunuz?", a: "Evet. Sezonluk ve yıllık güncelleme paketleri mevcuttur." },
				],
			},
			web: {
				title: "Torba Web Tasarım ve Yazılım",
				metaDesc: "Torba'da profesyonel web tasarım. Tatil köyü, villa kiralama ve aile oteli için SEO uyumlu web siteleri. Bodrum Torba. Cihan Duran.",
				heroDesc: "Torba'daki tesis veya villa kiralama işletmenizi dijitalde doğru konumlandırın, direkt rezervasyonla komisyon ödeyin.",
				badges: ["Tatil Köyü", "Villa Kiralama", "Aile Oteli", "SEO", "Rezervasyon", "Bodrum"],
				intro: "'Torba villa kiralama', 'Torba Bodrum tatil' aramalarında öne çıkmak; aile tatilcisi ve üst segment dinlenme arayan kitleyi doğru kanaldan çekmenizi sağlar.",
				details: "Torba'daki tatil tesisleri ve villa kiralama işletmelerine yönelik; aile dostu kullanıcı deneyimi, çok dilli içerik ve online rezervasyon sistemli web çözümleri sunuyoruz.",
				areas: [
					{ icon: "🏨", title: "Tatil Köyü Sitesi", desc: "Büyük tatil tesisleri için özellik sayfaları, galeri ve rezervasyon entegrasyonu." },
					{ icon: "🏡", title: "Villa Kiralama", desc: "Aile tatilcilerine yönelik, takvim ve rezervasyon sistemli villa kiralama siteleri." },
					{ icon: "🌊", title: "Körfez & Doğa Tanıtımı", desc: "Torba'nın sakin ve doğal atmosferini öne çıkaran içerik stratejisi." },
					{ icon: "📊", title: "Lokal SEO", desc: "Torba ve Bodrum çevresi anahtar kelimeleri için SEO optimizasyonu." },
				],
				faq: [
					{ q: "Tatil köyü için çok dilli site yapılabilir mi?", a: "Evet. Türkçe, İngilizce ve talebe göre Almanca dil desteği sunulmaktadır." },
					{ q: "Mevcut sitemiz var, sadece SEO hizmeti alabilir miyiz?", a: "Evet. Sadece lokal SEO danışmanlığı ve teknik optimizasyon hizmeti de sunulmaktadır." },
				],
			},
			design: {
				title: "Torba Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Torba'da profesyonel grafik tasarım. Tatil köyü, villa kiralama ve aile oteli için logo ve kurumsal kimlik tasarımı. Cihan Duran.",
				heroDesc: "Torba'nın huzurlu ve doğal atmosferini yansıtan, aile tatilcisine güven veren marka kimliği tasarımları.",
				badges: ["Logo", "Tatil Köyü", "Villa", "Aile", "Doğa", "Huzur"],
				intro: "Torba'daki bir tatil tesisi veya villa kiralama markasının görsel kimliği; huzur, güven ve doğallık duygularını aktarmalıdır. Bu değerler doğru müşteriyi çeker ve sadakati artırır.",
				details: "Yumuşak renk paletleri, su ve doğa temalarını çağrıştıran tipografi ve Torba'nın sakin ruhuyla örtüşen tasarım anlayışıyla özgün kimlikler oluşturuyoruz.",
				areas: [
					{ icon: "🏨", title: "Tatil Tesis Markası", desc: "Büyük tatil tesisleri için kurumsal ve tutarlı marka kimliği." },
					{ icon: "🏡", title: "Villa & Kiralama Markası", desc: "Aile tatilcisine güven ve konfor hissi veren villa kiralama logoları." },
					{ icon: "🌊", title: "Su & Doğa Temalı", desc: "Körfez ve doğa ile uyumlu renk ve biçim çalışmaları." },
					{ icon: "🖨️", title: "Baskı & Tabela", desc: "Tesis içi yönlendirme, broşür ve tanıtım materyalleri." },
				],
				faq: [
					{ q: "Tatil köyünün her birimi için ayrı alt marka oluşturabilir misiniz?", a: "Evet. Ana marka çatısı altında alt marka sistemleri tasarlanabilir." },
					{ q: "Tasarımlarınız hem dijital hem baskıda kullanılabilir mi?", a: "Evet. Tüm dosyalar RGB ve CMYK formatlarında teslim edilir." },
				],
			},
		},
	},

	ortakent: {
		name: "Ortakent-Yahşi",
		region: "Bodrum",
		slug: "ortakent",
		lat: "37.0094",
		lng: "27.3339",
		description: "Ortakent-Yahşi, Bodrum'un en uzun plajına ev sahipliği yapan, rüzgar ve kite sörfü tutkunlarının yanı sıra aile tatilcilerinin de tercih ettiği sakin bir destinasyondur.",
		services: {
			drone: {
				title: "Ortakent-Yahşi Drone Çekimi",
				metaDesc: "Ortakent-Yahşi'de profesyonel drone çekimi. Bodrum'un en uzun plajı, villa ve kıyı mülkleri için hava fotoğrafı ve 4K video. Cihan Duran.",
				heroDesc: "Ortakent-Yahşi'nin Bodrum'un en uzun plajını, rüzgar sörfü alanlarını ve kıyı boyunca uzanan yapılaşmayı havadan görüntüleyin.",
				badges: ["Yahşi Plajı", "Rüzgar Sörfü", "Villa", "Kıyı", "Bodrum", "4K"],
				intro: "Yahşi plajı, Bodrum'un en uzun kumsalı olmasıyla su sporları tutkunlarının ve aile tatilcilerinin vazgeçilmezi haline gelmiştir. Bu uzun kıyı şeridinin tamamını yalnızca havadan bir çekim aktarabilir.",
				details: "Ortakent'teki villa sitelerinden Yahşi sahil şeridine, mandalina bahçeleriyle çevrili kırsal alanlardan koy manzaralı mülklere kadar geniş bir coğrafyada drone çekimi gerçekleştiriyoruz.",
				areas: [
					{ icon: "🏖️", title: "Yahşi Plajı", desc: "Bodrum'un en uzun plajını kapsayan geniş alan hava çekimleri." },
					{ icon: "🪁", title: "Rüzgar & Kite Sörfü", desc: "Rüzgar sporları aktivitelerini belgeleyen dinamik çekimler." },
					{ icon: "🏡", title: "Villa & Kıyı Mülkleri", desc: "Ortakent'teki sahile yakın villa ve mülkler için satış çekimleri." },
					{ icon: "🌅", title: "Panoramik Kıyı", desc: "Ortakent-Yahşi'nin tüm kıyı şeridini kapsayan panoramik çekimler." },
				],
				faq: [
					{ q: "Ortakent'te rüzgarlı günler drone çekimini etkiler mi?", a: "Yahşi rüzgar sörfü için ideal olsa da drone çekiminde güçlü rüzgar kısıtlayıcıdır. Uygun günleri birlikte planlıyoruz." },
					{ q: "Kıyı boyunca uzun hat çekimi yapabilir misiniz?", a: "Evet. Yahşi plajının tüm uzunluğunu kapsayan hat çekimi gerçekleştirilmektedir." },
				],
			},
			photo: {
				title: "Ortakent-Yahşi Emlak ve Fotoğraf Çekimi",
				metaDesc: "Ortakent-Yahşi'de profesyonel emlak fotoğrafçılığı. Sahil yakını villa, tatil evi ve kıyı mülkleri için fotoğraf çekimi. Bodrum. Cihan Duran.",
				heroDesc: "Ortakent-Yahşi'deki mülkünüzü, sahile yakınlık avantajını öne çıkaran profesyonel görüntülerle sunun.",
				badges: ["Sahil Yakını", "Villa", "Tatil Evi", "Airbnb", "Aile", "Bodrum"],
				intro: "Ortakent-Yahşi'de sahile yakın konumun emlak değerini belirleyici etkisi büyüktür. Bu avantajı en iyi şekilde görsele aktarmak, doğru alıcı ve kiracıyı çekmenin anahtarıdır.",
				details: "Sabah güneşinin Yahşi plajına vurduğu anlarda veya öğleden sonra yumuşayan ışıkta; sahil manzaralı teraslar, bahçeler ve iç mekânları profesyonel ekipmanla fotoğraflıyoruz.",
				areas: [
					{ icon: "🏡", title: "Sahil Yakını Villa", desc: "Yahşi plajına yürüme mesafesindeki villa ve müstakil evler için çekimler." },
					{ icon: "🏠", title: "Tatil Evi & Apart", desc: "Airbnb ve tatil platformları için yüksek performanslı çekim paketleri." },
					{ icon: "🌊", title: "Deniz Manzaralı", desc: "Sahil veya deniz manzarasını ön plana çıkaran kompozisyonlar." },
					{ icon: "🍊", title: "Bahçeli Kırsal", desc: "Ortakent'in yeşil iç bölgelerindeki bahçeli ve doğa içindeki mülk çekimleri." },
				],
				faq: [
					{ q: "Sahile yürüme mesafesi olan bir mülkü fotoğrafta nasıl aktarıyorsunuz?", a: "Sahile gidiş güzergahı, çevre fotoğrafları ve drone'la mesafe gösterimi yapabiliriz." },
					{ q: "Ortakent'te en yüksek kira getirisini hangi mülk tipi sağlar?", a: "Sahile yakın ve hava koşullarına kapalı tatil evleri en yüksek getiriyi sunar; çekimde bunu ön plana çıkarıyoruz." },
				],
			},
			web: {
				title: "Ortakent-Yahşi Web Tasarım ve Yazılım",
				metaDesc: "Ortakent-Yahşi'de profesyonel web tasarım. Tatil kiralık, rüzgar sörfü okulu ve sahil işletmeleri için SEO uyumlu web siteleri. Cihan Duran.",
				heroDesc: "Ortakent-Yahşi'deki tatil kiralık veya su sporları işletmenizi dijitalde görünür kılın.",
				badges: ["Tatil Kiralık", "Rüzgar Sörfü", "Sahil", "SEO", "Aile Tatili", "Bodrum"],
				intro: "'Ortakent villa kiralama', 'Yahşi tatil evi', 'Bodrum windsurfing' gibi arama sorgularında görünür olmak, doğru kitleyi doğru zamanda yakalamanızı sağlar.",
				details: "Ortakent-Yahşi'deki tatil kiralık mülk sahiplerinden su sporları merkezlerine kadar geniş bir yelpazede; lokal SEO, çok dilli içerik ve rezervasyon sistemi entegrasyonlu web çözümleri sunuyoruz.",
				areas: [
					{ icon: "🏡", title: "Tatil Kiralık Sitesi", desc: "Direkt rezervasyon ve takvim sistemi entegrasyonlu tatil evi siteleri." },
					{ icon: "🪁", title: "Su Sporları Merkezi", desc: "Rüzgar sörfü ve kitesurf okulları için ders rezervasyonu ve tanıtım siteleri." },
					{ icon: "🏖️", title: "Sahil İşletmesi", desc: "Plaj restoranı ve cafe gibi sahil işletmeleri için uygun maliyetli web siteleri." },
					{ icon: "📊", title: "Lokal SEO", desc: "Ortakent ve Yahşi odaklı düşük rekabetli anahtar kelime çalışması." },
				],
				faq: [
					{ q: "Ortakent için lokal SEO'da rekabet durumu nasıl?", a: "Ortakent ve Yahşi özelinde anahtar kelimeler düşük rekabetlidir; sonuç görece hızlı alınabilir." },
					{ q: "Sadece tek bir tatil evim için site mantıklı mı?", a: "Evet. Tek mülk için bile OTA komisyonunu bypass eden direkt rezervasyon sitesi hızla amorti olur." },
				],
			},
			design: {
				title: "Ortakent-Yahşi Grafik Tasarım — Logo ve Marka Kimliği",
				metaDesc: "Ortakent-Yahşi'de profesyonel grafik tasarım. Tatil kiralık, su sporları ve sahil işletmeleri için logo ve kurumsal kimlik. Cihan Duran.",
				heroDesc: "Ortakent-Yahşi'nin aile dostu ve aktif tatil ruhunu yansıtan, akılda kalıcı marka tasarımları.",
				badges: ["Logo", "Tatil Evi", "Su Sporları", "Sahil", "Aile", "Sade"],
				intro: "Ortakent-Yahşi'deki tatil kiralık mülk veya su sporları işletmesinin markası; enerjik, güvenilir ve aile dostu bir imaj çizmelidir. Bu imaj doğru müşteriyi çeker.",
				details: "Plaj ve su sporları temalarını, aile tatili atmosferini yansıtan sade ve işlevsel tasarım çözümleri üretiyoruz. Küçük bütçeli projeler de dahil.",
				areas: [
					{ icon: "🏠", title: "Tatil Evi Markası", desc: "Misafirlere güven veren sade ve akılda kalıcı tatil evi logosu." },
					{ icon: "🪁", title: "Su Sporları Markası", desc: "Dinamizm ve doğa duygularını aktaran kitesurf ve windsurf okulu kimlikleri." },
					{ icon: "🏖️", title: "Sahil İşletmesi", desc: "Restoran, kafe ve sahil işletmeleri için ortamla uyumlu marka tasarımı." },
					{ icon: "📱", title: "Sosyal Medya", desc: "Tatil sezonu boyunca kullanılacak içerik ve kampanya şablonları." },
				],
				faq: [
					{ q: "Tek bir tatil evi için logo yaptırmak mantıklı mı?", a: "Evet. Güçlü bir logo, Airbnb profilinizi rakiplerden ayrıştırır ve güven oluşturur." },
					{ q: "Su sporları okulu için animasyonlu logo yapılabilir mi?", a: "Evet. Web ve sosyal medyada kullanılmak üzere animasyonlu versiyon üretilebilir." },
				],
			},
		},
	},
};

export const serviceLabels = {
	drone: { label: "Drone Çekimi", slug: "drone-cekimi", color: "#58a6ff", icon: "🚁" },
	photo: { label: "Emlak & Tekne Fotoğraf", slug: "emlak-tekne-fotograf", color: "#d29922", icon: "📸" },
	web: { label: "Web Tasarım & Yazılım", slug: "web-tasarim-yazilim", color: "#3fb950", icon: "💻" },
	design: { label: "Grafik Tasarım", slug: "grafik-tasarim", color: "#a371f7", icon: "🎨" },
};
